language: node_js

node_js:
  - "12"

git:
  depth: 1

branches:
  only:
    - master

before_install:
  - if [[ $TRAVIS_EVENT_TYPE == "cron" ]]; then
      exit;
    fi
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -k "$ssh_key_decrypt_password" -in id_rsa.enc -out $HOME/.ssh/id_rsa -d
  - chmod 600 $HOME/.ssh/id_rsa
  - ssh-add $HOME/.ssh/id_rsa
  - git config --global user.email bot@example.com
  - git config --global user.name bot
  - git remote set-url origin git@github.com:2049bbs/2049bbs.github.io.git

install:
  - npm install

before_script:
  - if [[ $TRAVIS_EVENT_TYPE == "push" && $TRAVIS_COMMIT_MESSAGE != *"[skip waiting]"* ]]; then
      for i in {20..1};
      do
        echo "Waiting. $i minute(s) left.";
        sleep 60;
      done;
    fi
  - git fetch
  - git checkout -f master

script:
  - npm run backup
  - git pull
  - git add .
  - git commit -m "$(date --iso-8601=minutes -u)"
  - git push
